[package]
name = "distill-loader"
version = "0.0.2"
authors = ["Karl Bergström <karl.anton.bergstrom@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Loader component of the asset pipeline `distill`."

[dependencies]
crossbeam-channel = "0.5.0"
distill-core = { path = "../core", version = "=0.0.2", features = ["serde-1"] }
distill-schema = { path = "../schema", version = "=0.0.2", optional = true }
bevy_tasks = "0.5.0"
async-net = "1.5.0"
async-channel = "1.6.1"
futures-util = { version = "0.3", default-features = false, features = ["io"], optional = true }
futures-channel = { version = "0.3", default-features = false, features = ["alloc"] }
futures-core = { version = "0.3", default-features = false, features = ["alloc"] }
capnp = { version = "0.14.0", optional = true }
capnp-rpc = { version = "0.14.0", optional = true }
log = "0.4"
dashmap = "4.0.1"
serde = { version = "1", features = ["derive"], optional = true }
uuid = { version = "0.8.2", optional = true }
memmap = { version = "0.7", optional = true }
thread_local = { version = "1.0", optional = true }


[features]
default = ["rpc_io", "handle", "packfile_io"]
packfile_io = [
    "distill-schema",
    "capnp",
    "capnp-rpc",
    "futures-util",
    "memmap",
    "thread_local",
]
rpc_io = [
    "distill-schema",
    "capnp",
    "capnp-rpc",
    "futures-util",
    "invalidate_path",
]
invalidate_path = ["distill-core/path_utils"]
handle = ["serde", "uuid"]
